name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main  # O la rama que uses

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Autenticarse en Firebase
        run: firebase use --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Generar build para producción
        run: flutter build web  # O el comando de build de tu stack

      - name: Desplegar en Firebase
        run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
