name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "$HOME/flutter/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: flutter pub get

    - name: Build web
      run: flutter build web

    - name: Deploy to Firebase
      run: |
        npm install -g firebase-tools
        firebase use --token "${{ secrets.FIREBASE_TOKEN }}"
        firebase deploy
